package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.example.flutter_asa.FlutterAsaPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_asa, com.example.flutter_asa.FlutterAsaPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin integration_test, dev.flutter.plugins.integration_test.IntegrationTestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.ip_location.IpLocationPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin ip_location, com.example.ip_location.IpLocationPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.net_dio_request.NetDioRequestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin net_dio_request, com.example.net_dio_request.NetDioRequestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_storage_tool.QsStorageToolPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_storage_tool, com.example.qs_storage_tool.QsStorageToolPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_toast.QsToastPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_toast, com.example.qs_toast.QsToastPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin shared_preferences_android, io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin", e);
    }
  }
}
